### PR TITLE
fix missing constants by requiring 'guard/compat/plugin'

### PR DESCRIPTION
**Pull request by knowtheory**
Hey folks,

We're the maintainers of jammit (and DocumentCloud).  We've been using `guard-jammit` for a while and just noticed after upgrading to the newest version of guard that the current `guard-jammit` gem is pretty far out of date.

We were wondering whether @reefdog & I could help with the maintenance and release process of `guard-jammit`, especially as we're getting back to maintaining jammit in an active fashion.

we dig guard, so thanks for creating it :)

### CODE REVIEW

**Comment by e2** [comment]
@pelle, @effkay - you can add me as a gem owner (cezary.baginski@gmail.com), since I'm responsible for Guard API and backward compatibility anyway.

**Comment by knowtheory** [comment]
We're happy to help out in whatever way we can too (and if that involves cutting gems we're happy to)

@e2 is just including the plugin compat the right way to have gone about doing this?

**Comment by e2** [comment]
@knowtheory - basically if it follows Guard::Compat's Readme instructions (which is what I myself went through every time - even though I wrote that myself), you should be fine.

Technically, the gem shouldn't need to depend on Guard, but it doesn't matter for guard-jammit. The patch shouldn't be necessary, but it's "good practice" overall for Guard plugins.

Anyway, it's probably vacation time so getting access may take time - I'll see what I can do.

**Comment by e2** [comment]
@knowtheory - I've invited you to this project and I've released guard-jammit v1.2.0. CC me whenever you need a release.

**Comment by knowtheory** [comment]
Awesome!  Thanks for the heads up.  We're working on a release of Jammit itself (a few issues to work through) and then we'll be back in touch! :)

(right now we're just pegging to DocumentCloud's copy of guard-jammit)  Also we got the SCSS compilation for Jammit working again!

**Pull request merged**
